
#ifndef WIRING_H
#define WIRING_H

#define ADDR_TOP 0x61
#define ADDR_BOT 0x60

#define BOT_PORT_FL 1
#define BOT_PORT_FR 4
#define BOT_PORT_BL 2
#define BOT_PORT_BR 3

#define PIN_ULTRASONIC_ECHO_LEFT 11
#define PIN_ULTRASONIC_ECHO_FRONT 12
#define PIN_ULTRASONIC_ECHO_RIGHT 10
#define PIN_ULTRASONIC_ECHO_BACK 9
#define PIN_ULTRASONIC_TRIG 8

#define TOTAL_SWITCH_COUNT 6

#define PIN_SWITCH_FRONT 2
#define PIN_SWITCH_RIGHT_F 3
#define PIN_SWITCH_RIGHT_B 4
#define PIN_SWITCH_BACK 5
#define PIN_SWITCH_LEFT_BACK 6
#define PIN_SWITCH_LEFT_FRONT 7

#define OFFSET_FL -1
#define OFFSET_FR -1
#define OFFSET_BL -1
#define OFFSET_BR -1

#endif
